# Generated by Django 4.2.7 on 2023-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rate_limit', models.PositiveIntegerField(max_length=5)),
                ('custom_endpoint', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
