# Generated by Django 4.2.7 on 2023-11-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
